#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: ${GOOGLE_CLIENT_SCOPE}
#
#          github:
#            clientId: ${GITHUB_CLIENT_ID}
#            clientSecret: ${GITHUB_CLIENT_SECRET}
